pub const LEVELS: [[&str; 17]; 3] = [
    [
        "XXXXX     XXXXXXXX     XXXXX",
        "",
        "",
        "",
        "",
        "   XXXXXXX        XXXXXXX   ",
        "",
        "",
        "",
        "   XXXXXXXXXXXXXXXXXXXXXX   ",
        "",
        "",
        "",
        "XXXXXXXXX          XXXXXXXXX",
        "",
        "",
        "",
    ],
    [
        "XXXX    XXXXXXXXXXXX    XXXX",
        "",
        "",
        "",
        "",
        "    XXXXXXXXXXXXXXXXXXXX    ",
        "",
        "",
        "",
        "XXXXXX                XXXXXX",
        "      X              X      ",
        "       X            X       ",
        "        X          X        ",
        "         X        X         ",
        "",
        "",
        "",
    ],
    [
        "XXXX    XXXX    XXXX    XXXX",
        "",
        "",
        "",
        "",
        "  XXXXXXXX        XXXXXXXX  ",
        "",
        "",
        "",
        "XXXX      XXXXXXXX      XXXX",
        "",
        "",
        "",
        "    XXXXXX        XXXXXX    ",
        "",
        "",
        "",
    ],
];
